import { StyleSheet, Platform } from "react-native";
import { useAppTheme } from "@/lib/theme";

export const createStyles = (theme: ReturnType<typeof useAppTheme>, insets: { top: number; bottom: number; left: number; right: number }) =>
  StyleSheet.create({
    rowSelected: {
      backgroundColor: theme.colors.selectionModeBackground,
    },
    header: {
      backgroundColor: theme.colors.header,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      paddingHorizontal: 12,
      height: 58, // STRICT FIXED HEIGHT
    },
    headerButton: {
      width: 40,
      height: 40,
      borderRadius: theme.radius.pill,
      alignItems: "center",
      justifyContent: "center",
    },
    headerButtonSmall: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.pill,
      alignItems: "center",
      justifyContent: "center",
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: {
      color: theme.colors.headerIcon,
      fontWeight: "800",
    },
    headerCopy: {
      flex: 1,
    },
    title: {
      color: theme.colors.headerText,
      fontSize: 18,
      fontWeight: "700",
    },
    subtitle: {
      color: theme.colors.headerSubtitle,
      fontSize: 12,
      marginTop: 1,
    },
    selectionCount: {
      color: theme.colors.headerText,
      fontSize: 20,
      fontWeight: "700",
      marginLeft: 4,
    },
    selectionActions: {
      flexDirection: "row",
      alignItems: "center",
      marginLeft: "auto",
      gap: 2,
    },
    searchBar: {
      backgroundColor: theme.colors.surface,
      marginHorizontal: theme.spacing.md,
      marginTop: theme.spacing.sm,
      borderRadius: theme.radius.pill,
      paddingHorizontal: 14,
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    searchInput: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 14,
      paddingVertical: 10,
    },

    thread: {
      flex: 1,
      backgroundColor: "transparent",
      overflow: "hidden",
    },
    backgroundLayer: {
      ...StyleSheet.absoluteFillObject,
      transform: [{ scale: 1.8 }], // Increase scale for zoomed doodles on mobile
      zIndex: -1,
    },
    backgroundImage: {
      width: "100%",
      height: "100%",
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 0,
      paddingVertical: theme.spacing.md,
    },
    dateSeparator: {
      alignItems: "center",
      marginVertical: 12,
      width: "100%",
    },
    datePill: {
      backgroundColor: theme.colors.datePill,
      paddingHorizontal: 16,
      paddingVertical: 6,
      borderRadius: 12,
      shadowRadius: 1,
      elevation: 1,
      shadowColor: "#000",
    },
    datePillText: {
      color: theme.colors.datePillText,
      fontSize: 12.5,
      fontWeight: "400",
    },
    unreadSeparator: {
      alignItems: "center",
      justifyContent: "center",
      marginVertical: 12,
      width: "100%",
    },
    unreadPill: {
      backgroundColor: theme.colors.bubbleBackground,
      paddingHorizontal: 16,
      paddingVertical: 5,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.bubbleBorder,
    },
    unreadPillText: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    emptyState: {
      marginTop: "auto",
      marginBottom: "auto",
      alignSelf: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      gap: 4,
      borderColor: theme.colors.separator,
      borderWidth: 1,
    },
    emptyTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
      textAlign: "center",
    },
    emptySubtitle: {
      color: theme.colors.textMuted,
      textAlign: "center",
      lineHeight: 20,
    },
    overlayRoot: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 100, // Increased z-index
      justifyContent: "flex-start",
      alignItems: "flex-end",
      paddingEnd: 8,
    },
    overlayRootCenter: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 100,
      justifyContent: "center",
      alignItems: "center",
      padding: theme.spacing.xl,
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.colors.overlay,
    },
    menuCard: {
      marginTop: insets.top + 56, // status bar + header height → right below the 3-dot button
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.md,
      width: 240,
      overflow: "hidden",
      shadowColor: "#000000",
      shadowOpacity: 0.18,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 5,
    },
    menuItem: {
      paddingHorizontal: 20,
      paddingVertical: 14,
      width: "100%",
      alignSelf: "stretch",
    },
    menuItemText: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
      textAlign: "left",
    },
    menuItemSecondary: {
      color: theme.colors.textMuted,
      fontSize: 12,
      marginTop: 3,
      textAlign: "left",
    },
    sheetCard: {
      marginTop: "auto",
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: theme.radius.xl,
      borderTopRightRadius: theme.radius.xl,
      paddingHorizontal: theme.spacing.md,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.xl,
      gap: 2,
    },
    sheetTitle: {
      color: theme.colors.text,
      fontSize: 18,
      fontWeight: "800",
      marginBottom: 8,
    },
    sheetButton: {
      paddingVertical: 14,
    },
    sheetButtonText: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "600",
    },
    sheetButtonDanger: {
      color: theme.colors.danger,
    },
    deleteModalCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      width: "100%",
      maxWidth: 320,
      padding: 24,
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 15,
      elevation: 20,
    },
    deleteModalTitle: {
      color: theme.colors.text,
      fontSize: 17,
      fontWeight: "600",
      marginBottom: 20,
      textAlign: "right",
    },
    deleteModalActions: {
      gap: 16,
      alignItems: "flex-end",
    },
    deleteModalAction: {
      paddingVertical: 8,
    },
    deleteModalActionText: {
      color: "#00A884", // WhatsApp green
      fontSize: 16,
      fontWeight: "700",
    },
    fullscreenOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.colors.background,
      zIndex: 200,
    },
    infoTitleRow: {
      height: 58,
      backgroundColor: theme.colors.header,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      gap: 16,
    },
    infoTitle: {
      color: theme.colors.headerText,
      fontSize: 20,
      fontWeight: "700",
      textAlign: "right",
      flex: 1,
    },
    infoScroll: {
      paddingBottom: 40,
    },
    infoBubbleRow: {
      paddingVertical: 20,
      backgroundColor: theme.colors.surfaceAlt,
    },
    infoSection: {
      paddingHorizontal: 24,
      marginTop: 24,
    },
    infoSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 16,
    },
    infoSectionTitle: {
      color: "#00A884",
      fontSize: 15,
      fontWeight: "700",
    },
    infoUserRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      marginBottom: 20,
    },
    infoUserText: {
      flex: 1,
    },
    infoUsername: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "600",
      textAlign: "right",
    },
    infoUserTime: {
      color: theme.colors.textMuted,
      fontSize: 13,
      textAlign: "right",
      marginTop: 2,
    },
    reactionsSheet: {
      marginTop: "auto",
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 40,
      minHeight: 400,
      width: "100%",
    },
    sheetHandle: {
      width: 40,
      height: 4,
      backgroundColor: theme.colors.sheetHandle,
      borderRadius: 2,
      alignSelf: "center",
      marginTop: 12,
    },
    reactionsSheetHeader: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
      textAlign: "right",
      padding: 24,
    },
    reactionTabs: {
      flexDirection: "row",
      paddingHorizontal: 24,
      marginBottom: 16,
      borderBottomWidth: 1,
      borderColor: theme.colors.separator,
    },
    reactionTabActive: {
      paddingBottom: 12,
      borderBottomWidth: 3,
      borderColor: "#00A884",
    },
    reactionTabText: {
      color: "#00A884",
      fontSize: 15,
      fontWeight: "700",
    },
    reactionUserList: {
      paddingHorizontal: 24,
    },
    reactionUserRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
    },
    reactionUserInfo: {
      flex: 1,
    },
    reactionUserName: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "600",
      textAlign: "right",
    },
    reactionUserAction: {
      color: theme.colors.textMuted,
      fontSize: 13,
    },
    reactionEmoji: {
      fontSize: 22,
    },
    emojiPickerSheet: {
      marginTop: "auto",
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 40,
      height: "70%",
      width: "100%",
    },
    emojiPickerSearch: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.searchBackground,
      margin: 20,
      borderRadius: 30,
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 12,
    },
    emojiPickerSearchText: {
      color: theme.colors.textMuted,
      fontSize: 16,
    },
    emojiCategoryTitle: {
      color: theme.colors.textMuted,
      fontSize: 13,
      fontWeight: "700",
      textAlign: "right",
      paddingHorizontal: 24,
      marginBottom: 16,
    },
    emojiGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 16,
    },
    emojiCell: {
      width: "14.28%", // 7 columns
      aspectRatio: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    emojiCellText: {
      fontSize: 28,
    },
    backdropDark: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    dialogCard: {
      width: "100%",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      padding: theme.spacing.xl,
    },
    dialogTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.md,
      textAlign: "right",
    },
    dialogTitleSmall: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.colors.text,
      marginBottom: theme.spacing.lg,
      textAlign: "right",
    },
    dialogSub: {
      fontSize: 15,
      color: theme.colors.textMuted,
      marginBottom: theme.spacing.lg,
      textAlign: "right",
      lineHeight: 22,
    },
    dialogSubBold: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.textMuted,
      marginBottom: theme.spacing.lg,
      textAlign: "right",
      lineHeight: 24,
    },
    radioRow: {
      flexDirection: "row-reverse",
      alignItems: "center",
      paddingVertical: theme.spacing.md,
      gap: theme.spacing.md,
    },
    radioOut: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: theme.colors.textMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    radioOutActive: {
      borderColor: theme.colors.accent,
    },
    radioIn: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: theme.colors.accent,
    },
    radioText: {
      fontSize: 16,
      color: theme.colors.text,
      flex: 1,
      textAlign: "right",
    },
    checkRow: {
      flexDirection: "row-reverse",
      alignItems: "flex-start",
      paddingVertical: theme.spacing.md,
      gap: theme.spacing.md,
    },
    checkBox: {
      width: 20,
      height: 20,
      borderWidth: 2,
      borderColor: theme.colors.textMuted,
      borderRadius: 4,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    checkBoxActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    dialogFooterNotes: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: "right",
      marginTop: theme.spacing.lg,
      marginBottom: theme.spacing.xl,
      lineHeight: 18,
    },
    dialogFullBtn: {
      borderWidth: 1,
      borderColor: "red",
      borderRadius: theme.radius.pill,
      paddingVertical: 12,
      alignItems: "center",
    },
    dialogFullBtnText: {
      color: "red",
      fontSize: 16,
      fontWeight: "600",
    },
    dialogActions: {
      flexDirection: "row",
      justifyContent: "flex-start",
      gap: theme.spacing.xl,
      marginTop: theme.spacing.xl,
    },
    dialogActionsExpand: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: theme.spacing.lg,
    },
    dialogBtn: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.accent,
      padding: theme.spacing.sm,
    },
    attachmentMenuCard: {
      position: "absolute",
      bottom: 70,
      left: 12,
      right: 12,
      backgroundColor: theme.colors.menuBackground,
      borderRadius: 16,
      paddingVertical: 18,
      paddingHorizontal: 8,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 20,
    },
    attachmentRow: {
      flexDirection: "row-reverse",
      justifyContent: "space-around",
      alignItems: "flex-start",
      marginBottom: 20,
    },
    attachmentItem: {
      width: 70,
      alignItems: "center",
      gap: 8,
    },
    attachmentIconCircle: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.menuIconBackground,
    },
    attachmentLabel: {
      color: theme.colors.menuTextSecondary,
      fontSize: 13,
      textAlign: "center",
      fontWeight: "500",
    },
    toastContainer: {
      position: "absolute",
      bottom: Platform.OS === "ios" ? 100 : 80,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 1000,
    },
    toastPill: {
      backgroundColor: theme.colors.datePill,
      borderRadius: 30,
      paddingHorizontal: 20,
      paddingVertical: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 10,
    },
    toastIcon: {
      width: 20,
      height: 20,
    },
    toastText: {
      color: theme.colors.datePillText,
      fontSize: 14,
      fontWeight: "600",
    },
  });
