import { Platform, StyleSheet } from "react-native";
import { useAppTheme } from "@/lib/theme";
import { useSafeAreaInsets } from "react-native-safe-area-context";

export const createStyles = (theme: ReturnType<typeof useAppTheme>, insets: ReturnType<typeof useSafeAreaInsets>, scheme: "light" | "dark" | null | undefined) =>
  StyleSheet.create({
    page: {
      flex: 1,
      backgroundColor: theme.colors.homeBackground,
      paddingTop: Math.max(0, insets.top - 20),
    },
    header: {
      minHeight: 64,
      backgroundColor: theme.colors.homeHeader,
      position: "relative",
    },
    headerInner: {
      flex: 1,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.spacing.md,
      paddingTop: 4,
      paddingBottom: 10,
      position: "relative",
    },
    headerActions: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      gap: 2,
      ...(Platform.OS !== "web"
        ? ({
            position: "absolute",
            right: theme.spacing.md,
            top: 4,
            bottom: 10,
            alignItems: "center",
          } as any)
        : null),
    },
    selectionHeader: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: theme.colors.homeHeader,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.md,
      zIndex: 5,
      paddingTop: 4,
      paddingBottom: 10,
    },
    brand: {
      flex: Platform.OS === "web" ? 1 : 0,
      color: scheme === "dark" ? "#F3F4F6" : "#1EA860",
      fontSize: 22,
      fontWeight: "700",
      textAlign: "right",
      writingDirection: "rtl",
      ...(Platform.OS !== "web"
        ? ({
            position: "absolute",
            left: theme.spacing.md,
            top: 0,
            bottom: 6,
            textAlignVertical: "center",
          } as any)
        : null),
    },
    selectionTitle: {
      color: theme.colors.text,
      fontSize: 24,
      fontWeight: "800",
      marginLeft: 10,
    },
    selectionActions: {
      marginLeft: Platform.OS === "web" ? 0 : "auto",
      marginRight: Platform.OS === "web" ? "auto" : 0,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 2,
    },
    iconButton: {
      width: 38,
      height: 38,
      borderRadius: theme.radius.pill,
      alignItems: "center",
      justifyContent: "center",
    },
    searchShell: {
      marginHorizontal: theme.spacing.md,
      marginTop: 0,
      marginBottom: 6,
      backgroundColor: scheme === "dark" ? theme.colors.homeSearch : "#F6F5F3",
      borderRadius: theme.radius.xl,
      minHeight: 46,
      paddingHorizontal: 16,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 10,
    },
    filterBar: {
      marginTop: 20,
      marginBottom: 12,
    },
    filterScroll: {
      paddingHorizontal: theme.spacing.md,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      flexGrow: 1,
      justifyContent: Platform.OS === "web" ? "flex-start" : "flex-start",
      minWidth: "100%",
    },
    addFilterBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.homeSearch,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
    },
    searchInput: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15,
      paddingVertical: 10,
      textAlign: "right",
      writingDirection: "rtl",
    },
    scrollContent: {
      paddingBottom: 90,
    },
    sectionButton: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 11,
      backgroundColor: theme.colors.homeRow,
    },
    sectionLeft: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 12,
    },
    sectionIconContainer: {
      width: 54,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: "center",
      justifyContent: "center",
    },
    sectionLabel: {
      color: scheme === "dark" ? theme.colors.text : "#5E676A",
      fontSize: 17,
      fontWeight: "700",
      textAlign: "right",
      writingDirection: "rtl",
    },
    sectionRight: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 8,
    },
    sectionCount: {
      color: theme.colors.textMuted,
      fontSize: 13,
      fontWeight: "700",
    },
    statusText: {
      color: theme.colors.textMuted,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 10,
    },
    chatRow: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 12,
      paddingLeft: theme.spacing.md,
      paddingRight: theme.spacing.md,
      paddingVertical: 11,
      backgroundColor: theme.colors.homeRow,
    },
    chatRowSelected: {
      backgroundColor: theme.colors.homeSelection,
    },
    avatarWrap: {
      position: "relative",
    },
    avatar: {
      width: 54,
      height: 54,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: {
      color: theme.colors.accent,
      fontSize: 20,
      fontWeight: "800",
    },
    selectedBadge: {
      position: "absolute",
      right: -2,
      bottom: -2,
      width: 22,
      height: 22,
      borderRadius: theme.radius.pill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.accentStrong,
      borderWidth: 2,
      borderColor: theme.colors.homeRow,
    },
    chatMain: {
      flex: 1,
      justifyContent: "center",
      minWidth: 0,
    },
    chatTopRow: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      justifyContent: "space-between",
      gap: theme.spacing.sm,
    },
    titleWrap: {
      flex: 1,
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 6,
      minWidth: 0,
    },
    chatTitle: {
      flexShrink: 1,
      color: theme.colors.text,
      fontSize: 17,
      fontWeight: "700",
      textAlign: "right",
      writingDirection: "rtl",
    },
    trailingWrap: {
      alignItems: Platform.OS === "web" ? "flex-start" : "flex-end",
      gap: 6,
    },
    chatTime: {
      color: theme.colors.textMuted,
      fontSize: 12,
    },
    chatTimeUnread: {
      color: theme.colors.accent,
      fontWeight: "700",
    },
    unreadBadge: {
      minWidth: 22,
      height: 22,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.accentStrong,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 6,
    },
    unreadBadgeText: {
      color: theme.colors.textOnAccent,
      fontSize: 11,
      fontWeight: "800",
    },
    chatPreview: {
      color: theme.colors.textMuted,
      fontSize: 14,
      marginTop: 4,
      textAlign: "right",
      writingDirection: "rtl",
    },
    chatPreviewUnread: {
      color: theme.colors.text,
      fontWeight: "600",
    },
    chatPreviewCleared: {
      fontStyle: "italic",
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.spacing.xl,
      paddingTop: 90,
      gap: 8,
    },
    emptyTitle: {
      color: theme.colors.text,
      fontSize: 20,
      fontWeight: "800",
    },
    emptySubtitle: {
      color: theme.colors.textMuted,
      textAlign: "center",
      lineHeight: 22,
    },
    overlayRoot: {
      ...StyleSheet.absoluteFillObject,
      top: -15,
      zIndex: 40,
      justifyContent: "flex-start",
      alignItems: "flex-end",
      paddingEnd: 10,
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.colors.overlay,
    },
    menuCard: {
      marginTop: 54 + insets.top,
      width: 230,
      borderRadius: theme.radius.md,
      overflow: "hidden",
      backgroundColor: theme.colors.surface,
      shadowColor: "#000000",
      shadowOpacity: 0.18,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
    },
    menuItem: {
      paddingHorizontal: 16,
      paddingVertical: 15,
      width: "100%",
      alignSelf: "stretch",
    },
    menuItemText: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: "700",
      textAlign: "right",
      writingDirection: "rtl",
    },
    menuItemDanger: {
      color: theme.colors.danger,
    },
    fab: {
      position: "absolute",
      bottom: 95 + insets.bottom,
      right: Platform.OS === "web" ? undefined : 20,
      left: Platform.OS === "web" ? 20 : undefined,
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: theme.colors.accentStrong || "#00A884",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    tabBar: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      backgroundColor: theme.colors.homeHeader,
      borderTopWidth: 0.5,
      borderTopColor: theme.colors.border,
      paddingBottom: insets.bottom,
      paddingTop: 10,
    },
    tabItem: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingBottom: 6,
      gap: 4,
    },
    tabIcon: {
      width: 34, // Increased from 32
      height: 34, // Increased from 32
      resizeMode: "contain",
    },
    tabIconWrap: {
      width: 64,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      overflow: "hidden",
    },
    tabIconWrapActive: {
      backgroundColor: scheme === "dark" ? "#0F3528" : "#D9FDD3",
    },
    tabLabel: {
      color: scheme === "dark" ? "#FFFFFF" : "#202123",
      fontSize: 14,
      fontWeight: "600",
      marginTop: 2,
    },
    tabLabelActive: {
      color: scheme === "dark" ? "#FFFFFF" : "#008069",
      fontWeight: "bold",
    },
    tabBadge: {
      position: "absolute",
      top: -4,
      right: -6,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: "#E53935",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 3,
    },
    tabBadgeText: {
      color: "#fff",
      fontSize: 10,
      fontWeight: "800",
    },
    // Screenshot request cards in Updates tab
    screenshotCard: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "flex-start",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: theme.colors.homeRow,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.colors.border,
    },
    screenshotAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#7B5000",
      alignItems: "center",
      justifyContent: "center",
    },
    screenshotAvatarText: {
      color: "#fff",
      fontWeight: "800",
      fontSize: 17,
    },
    screenshotCardTitle: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: "700",
    },
    screenshotCardGroup: {
      color: theme.colors.textMuted,
      fontSize: 13,
    },
    screenshotCardSub: {
      color: theme.colors.textMuted,
      fontSize: 12,
    },
    screenshotCardActions: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      gap: 10,
      marginTop: 4,
    },
    screenshotBtn: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 7,
      paddingHorizontal: 18,
      borderRadius: 20,
    },
    screenshotBtnApprove: {
      backgroundColor: "#1B9D55",
    },
    screenshotBtnDeny: {
      backgroundColor: "#C0392B",
    },
    screenshotBtnText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
    },
    screenshotMyCard: {
      flexDirection: Platform.OS === "web" ? "row-reverse" : "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "#3D2A00",
      borderBottomWidth: 0.5,
      borderBottomColor: "#C87F00",
    },
    screenshotMyTitle: {
      color: "#FFD580",
      fontWeight: "700",
      fontSize: 14,
    },
    screenshotMyChat: {
      color: "#FFA726",
      fontSize: 13,
    },
    screenshotMySub: {
      color: "#FFCC80",
      fontSize: 12,
    },
  });

export const chipStyles = StyleSheet.create({
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
  },
});
