import { StyleSheet } from "react-native";
import { useAppTheme } from "@/lib/theme";

export const createStyles = (theme: ReturnType<typeof useAppTheme>) =>
  StyleSheet.create({
    rowWrapper: {
      flex: 1,
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
      zIndex: 1,
    },
    swipeIconContainer: {
      position: "absolute",
      right: 15,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(0,0,0,0.08)",
      alignItems: "center",
      justifyContent: "center",
      zIndex: -1,
    },
    row: {
      flex: 1,
      flexDirection: "row",
      marginVertical: 1,
      paddingVertical: 2,
    },
    rowMine: {
      justifyContent: "flex-end",
    },
    rowTheirs: {
      justifyContent: "flex-start",
    },
    rowSystem: {
      justifyContent: "center",
    },
    rowSelected: {
      backgroundColor: "rgba(0,168,132,0.38)",
    },
    fullWidthSelection: {
      width: "100%",
      paddingHorizontal: 12,
    },
    bubble: {
      borderRadius: 12,
      maxWidth: "83%",
      minWidth: 180,
      paddingHorizontal: 9,
      paddingTop: 6,
      paddingBottom: 5,
      shadowColor: "#000000",
      shadowOpacity: theme.colors.background === "#0b141a" ? 0.16 : 0.05,
      shadowRadius: 2,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    bubbleMine: {
      backgroundColor: theme.colors.mine,
      borderTopRightRadius: 4,
      alignSelf: "flex-end",
    },
    bubbleTheirs: {
      backgroundColor: theme.colors.theirs,
      borderTopLeftRadius: 4,
      alignSelf: "flex-start",
    },
    systemBubble: {
      backgroundColor: theme.colors.surfaceAlt,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 4,
      maxWidth: "85%",
      alignSelf: "center",
      marginVertical: 4,
    },
    systemText: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: "center",
      fontWeight: "500",
    },
    author: {
      color: "#8b5cf6",
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 3,
    },
    replyBlock: {
      backgroundColor: theme.colors.background === "#0b141a" ? "rgba(0,0,0,0.25)" : "rgba(0,0,0,0.06)",
      borderRadius: 8,
      overflow: "hidden",
      marginBottom: 6,
      marginTop: 2,
    },
    replyBlockContent: {
      flexDirection: "row",
      alignItems: "stretch",
    },
    replyBlockTextContainer: {
      flex: 1,
      paddingVertical: 4,
      paddingHorizontal: 8,
      alignItems: "flex-end",
    },
    replyBlockAccent: {
      width: 4,
    },
    replyLabel: {
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 1,
    },
    replyBlockText: {
      color: theme.colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: "right",
    },
    body: {
      color: theme.colors.text,
      fontSize: 15,
      lineHeight: 20,
      textAlign: "auto",
      flexShrink: 1,
    },
    metaRow: {
      marginTop: 2,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    kindChip: {
      backgroundColor: theme.colors.surfaceAlt,
      borderRadius: theme.radius.pill,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    kindChipText: {
      color: theme.colors.textMuted,
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    timeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
    },
    meta: {
      color: theme.colors.textMuted,
      fontSize: 11,
      paddingRight: 3,
    },
    reactionPicker: {
      position: "absolute",
      top: -50,
      zIndex: 100,
    },
    pickerMine: {
      right: 0,
    },
    pickerTheirs: {
      left: 0,
    },
    pickerInner: {
      backgroundColor: theme.colors.surface,
      borderRadius: 30,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 10,
    },
    quickEmoji: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
    },
    quickEmojiPressed: {
      backgroundColor: theme.colors.surfaceAlt,
    },
    quickEmojiText: {
      fontSize: 22,
    },
    reactionPill: {
      position: "absolute",
      bottom: -18,
      backgroundColor: theme.colors.bubbleBackground,
      borderRadius: 16,
      borderColor: theme.colors.background,
      borderWidth: 2,
      paddingHorizontal: 4,
      paddingVertical: 1,
      flexDirection: "row",
      alignItems: "center",
      zIndex: 10,
    },
    reactionPillMine: {
      right: -4,
    },
    reactionPillTheirs: {
      right: -4,
    },
    reactionPillEmojis: {
      flexDirection: "row",
      alignItems: "center",
    },
    reactionPillEmoji: {
      fontSize: 12,
    },
    reactionPillCount: {
      color: theme.colors.textMuted,
      fontSize: 11,
      fontWeight: "700",
      marginLeft: 4,
    },
    pollCard: {
      backgroundColor: "transparent",
      minWidth: 240,
    },
    pollTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.colors.text,
      textAlign: "left",
      marginBottom: 6,
    },
    pollSubtitleWrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      marginBottom: 14,
      width: "100%",
    },
    pollSubtitle: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: "left",
      flex: 1,
      marginRight: 4,
    },
    pollOptionRow: {
      paddingVertical: 10,
      borderTopWidth: 0.5,
      borderColor: "rgba(255,255,255,0.1)",
      position: "relative",
      width: "100%",
    },
    pollOptionInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
    },
    pollOptionTextWrapper: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      justifyContent: "flex-start",
      gap: 12,
    },
    pollOptionText: {
      fontSize: 16,
      color: theme.colors.text,
      textAlign: "left",
      flex: 1,
      marginRight: 16,
    },
    pollRadioCircle: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: theme.colors.textMuted,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    pollRadioCircleChecked: {
      backgroundColor: theme.colors.accentStrong,
      borderColor: theme.colors.accentStrong,
      borderWidth: 0,
    },
    pollVoteCount: {
      color: theme.colors.textMuted,
      fontSize: 14,
      minWidth: 20,
      textAlign: "left",
    },
    pollProgressContainer: {
      height: 6,
      backgroundColor: "rgba(255,255,255,0.06)",
      borderRadius: 10,
      marginTop: 8,
      overflow: "hidden",
      width: "100%",
    },
    pollProgressBar: {
      height: "100%",
      backgroundColor: theme.colors.textMuted + "44", // Semi-transparent muted for general votes
      borderRadius: 3,
    },
    pollProgressBarChecked: {
      backgroundColor: theme.colors.accent,
    },
    pollFooter: {
      borderTopWidth: 1,
      borderColor: theme.colors.border,
      paddingVertical: 10,
      alignItems: "center",
      marginTop: 4,
    },
    pollFooterText: {
      color: theme.colors.accent,
      fontSize: 14,
      fontWeight: "500",
    },
  });
